FROM node:18-slim #used to tell docker what image to use as base when building

# add curl for healthcheck
# what build commands to run
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl tini && \
    rm -rf /var/lib/apt/lists/*

# changes the working directory
WORKDIR /usr/local/app

# have nodemon available for local dev use (file watching)
RUN npm install -g nodemon 

#Copies files and directories from location to container
COPY package*.json ./

RUN npm ci && \
 npm cache clean --force && \
 mv /usr/local/app/node_modules /node_modules

COPY . .

#sets env variables
ENV PORT=80

#tells your container what points to listen on
EXPOSE 80

#tells your server what executable to run 
ENTRYPOINT ["/usr/bin/tini", "--"]

#specifies default commands
CMD ["node", "server.js"]